const {chromium}=require('./browser.cjs');
const fs=require('node:fs');const reports=[];
const record=(id,nim)=>({id,nim,nama:'Mahasiswa '+nim,jenis:'Proposal',status:'Accepted',date:new Date().toISOString(),detail:'Judul '+nim,link:'',note:'[]'});
(async()=>{
const browser=await chromium.launch({});const context=await browser.newContext();let calls=[],delayRead=false,failRead=false;let releaseRead;let holdCreates=false;let createReleases=[];
await context.route('**/*',async route=>{
const url=route.request().url();if(url.includes('script.google.com/macros/')){
const data=route.request().postDataJSON();calls.push(data);let result;
if(data.action==='student_login'){await new Promise(r=>setTimeout(r,120));result={status:'success',token:'student-'+data.nim,nama:'Mahasiswa '+data.nim};}
else if(data.action==='admin_login')result={status:'success',token:'admin'};
else if(data.action==='get_data'){
result=failRead?{status:'error',message:'Server uji terganggu'}:{status:'success',registrations:data.token==='admin'?[record('a','A'),record('b','B')]:[record(data.token.slice(8),data.token.slice(8))],students:[],contents:[],announcements:[],dosens:[]};
if(delayRead){delayRead=false;await new Promise(r=>releaseRead=r);}
}
else if(data.action==='create'){if(holdCreates)await new Promise(r=>createReleases.push(r));result={status:'success',id:'created',date:new Date().toISOString()};}
else if(data.action==='post_announcement')result={status:'error',message:'Pengiriman gagal'};
else result={status:'success'};
return route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify(result)});
}
if(url.startsWith('http://127.0.0.1:8766'))return route.continue();if(url.includes('chart.js'))return route.fulfill({contentType:'text/javascript',body:'window.Chart=class {static defaults={font:{}}; static getChart(){return {resize(){}}}; destroy(){}; constructor(){};};'});return route.abort();
});
const page=await context.newPage();page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:8766');await page.fill('#input-nim','A');await page.locator('#input-nim').press('Enter');await page.locator('#input-nim').press('Enter');await page.waitForSelector('#welcome-modal',{state:'hidden'});await page.waitForFunction(()=>sessionStorage.getItem('ipcos_registrations'));reports.push({bug:'Repeated student login',observed:calls.filter(c=>c.action==='student_login').length});
await page.evaluate(()=>switchTab(null,'pendaftaran'));await page.selectOption('#reg-jenis-utama','Proposal');await page.fill('#reg-judul','ISIAN PRIVAT AKUN A');await page.setInputFiles('#file-acc-sempro',{name:'akun-a.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 PRIVATE')});await page.click('.btn-logout');await page.waitForSelector('#welcome-modal',{state:'visible'});await page.fill('#input-nim','B');await page.click('#form-mhs button');await page.waitForSelector('#welcome-modal',{state:'hidden'});await page.evaluate(()=>switchTab(null,'pendaftaran'));reports.push({bug:'Draft and files cross accounts',observed:await page.inputValue('#reg-judul'),files:await page.locator('#file-acc-sempro').evaluate(e=>e.files.length)});
await page.evaluate(()=>switchTab(null,'student-status'));failRead=true;await page.evaluate(()=>syncDatabase());reports.push({bug:'Refresh failure leaves loading placeholders',observed:await page.locator('#table-my-status .skeleton').count()});failRead=false;
await page.evaluate(()=>switchTab(null,'dashboard'));await page.click('.btn-logout');await page.waitForSelector('#welcome-modal',{state:'visible'});await page.click('#tab-admin');await page.fill('#input-admin-user','fixture');await page.fill('#input-admin-pass','fixture');await page.click('#form-admin button');await page.waitForSelector('#welcome-modal',{state:'hidden'});await page.waitForFunction(()=>JSON.parse(sessionStorage.getItem('ipcos_registrations')||'[]').length===2);
delayRead=true;await page.evaluate(()=>{syncDatabase();});while(!releaseRead)await new Promise(r=>setTimeout(r,10));await page.click('.btn-logout');await page.waitForSelector('#welcome-modal',{state:'visible'});await page.click('#tab-mhs');await page.fill('#input-nim','B');await page.click('#form-mhs button');await page.waitForSelector('#welcome-modal',{state:'hidden'});await page.waitForFunction(()=>JSON.parse(sessionStorage.getItem('ipcos_registrations')||'[]').length===1);releaseRead();await new Promise(r=>setTimeout(r,250));reports.push({bug:'Late admin response contaminates student cache',observed:await page.evaluate(()=>JSON.parse(sessionStorage.getItem('ipcos_registrations')||'[]').map(r=>r.nim))});
await page.evaluate(()=>switchTab(null,'admin-data'));reports.push({bug:'Student can navigate to admin interface',observed:await page.locator('#admin-data').evaluate(e=>e.classList.contains('active'))});
await page.click('.btn-logout');await page.waitForSelector('#welcome-modal',{state:'visible'});await page.click('#tab-admin');await page.fill('#input-admin-user','fixture');await page.fill('#input-admin-pass','fixture');await page.click('#form-admin button');await page.waitForSelector('#welcome-modal',{state:'hidden'});await page.locator('.dashboard-secondary summary').click();await page.fill('#input-broadcast-dashboard','PESAN JANGAN HILANG');await page.evaluate(()=>postAnnouncementFromDashboard());await new Promise(r=>setTimeout(r,150));reports.push({bug:'Failed announcement erases admin input',observed:await page.inputValue('#input-broadcast-dashboard')});
await page.evaluate(()=>openEditDosen('Dosen Uji',1,5));await page.fill('#edit-dosen-terpakai','-1');await page.fill('#edit-dosen-maksimal','0');await page.evaluate(()=>saveDosenQuota());reports.push({bug:'Invalid lecturer quota is submitted',observed:calls.filter(c=>c.action==='manage_dosen').at(-1)});

await page.evaluate(()=>closeModal('modal-edit-dosen',true));
async function switchStudent(nim){if(await page.locator('#loader').isVisible())await page.evaluate(()=>logoutUser());else await page.click('.btn-logout');await page.waitForSelector('#welcome-modal',{state:'visible'});await page.click('#tab-mhs');await page.fill('#input-nim',nim);await page.locator('#input-nim').press('Enter');await page.waitForSelector('#welcome-modal',{state:'hidden'});}
async function prepareCreate(){await page.evaluate(()=>switchTab(null,'pendaftaran'));await page.selectOption('#reg-jenis-utama','Proposal');await page.fill('#reg-judul','Pengajuan Uji');await page.setInputFiles('#file-acc-sempro',{name:'uji.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF TEST')});await page.click('#btn-review-registration');await page.click('#btn-submit-registration');}
await switchStudent('B');holdCreates=true;await prepareCreate();while(createReleases.length<1)await new Promise(r=>setTimeout(r,10));
await switchStudent('C');await prepareCreate();while(createReleases.length<2)await new Promise(r=>setTimeout(r,10));
createReleases[0]();await new Promise(r=>setTimeout(r,180));const oldCannotUnlock=await page.evaluate(()=>isSubmittingRegistration);require('node:assert/strict').equal(oldCannotUnlock,true);createReleases[1]();await page.waitForFunction(()=>!isSubmittingRegistration);reports.push({bug:'Upload from previous session blocks or unlocks new account submission',fixed:oldCannotUnlock});
fs.writeFileSync(__dirname+'/../test-results//after.json',JSON.stringify(reports,null,2));const assert=require('node:assert/strict'); assert.equal(reports[0].observed,1); assert.equal(reports[1].observed,''); assert.equal(reports[1].files,0); assert.equal(reports[2].observed,0); assert.deepEqual(reports[3].observed,['B']); assert.equal(reports[4].observed,false); assert.equal(reports[5].observed,'PESAN JANGAN HILANG'); assert.equal(reports[6].observed,undefined); console.log('PASS Eight regression scenarios passed'); console.log(JSON.stringify(reports,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
