const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium,reportFailure}=require('./browser.cjs'),fixture=require('./next-backend.fixture.cjs'),{previewPdf:pdf}=require('./fixtures.cjs');
const origin=process.env.IPCOS_TEST_ORIGIN||'http://127.0.0.1:8766',f=fixture(),calls=[],errors=[],results=[];
const url='https://drive.google.com/file/d/current/view';
f.rows[1][7]='Pending';f.rows[1][5]+="<br><br><b style='color:#E03F4F;'>Dosen Pembimbing:</b> Supervisor";f.rows[1][6]='<a href="'+url+'">Form ACC Seminar Proposal</a>';f.rows[1][8]=JSON.stringify([{role:'mhs',message:'Submitted',documents:[{url,label:'Form ACC Seminar Proposal',fileName:'acc.pdf',version:1}]}]);f.rows[2][7]='Accepted';
const doc={schema:1,type:'sop_magang',revision:1,updatedAt:'2026-10-09T01:00:00Z',title:'SOP Magang',titleEn:'Internship SOP',intro:'Panduan',introEn:'',sections:[{id:'one',title:'Persiapan',titleEn:'',body:'Dokumen wajib',bodyEn:'',links:[{id:'guide',label:'Panduan',labelEn:'',url:'https://example.com/guide'}],files:[]}]};
let oldBackend=false,lostReview=false,holdDocument=false,releaseDocument;
const pass=text=>{results.push(text);console.log('PASS '+text);};
async function mock(context){await context.route('**/*',async route=>{
    const target=route.request().url();if(target.includes('script.google.com/macros/')){
        const data=route.request().postDataJSON();calls.push(data);let result;
        if(data.action==='admin_login')result={status:'success',token:'admin'};
        else if(data.action==='student_login')result={status:'success',token:'student-A',nama:'Student Test'};
        else if(data.action==='get_data')result={status:'success',registrations:f.records().filter(item=>data.token==='admin'||item.nim==='A').map(item=>({...item,reviewVersion:f.ctx.nextRevisionVersion(item),detail:item.detail.split("<br><br><b style='color:#E03F4F;'>Dosen Pembimbing:")[0]})),students:[],dosens:[{Nama:'Supervisor',Maksimal:10,Terpakai:0}],contents:[],announcements:[],services:[]};
        else if(data.action==='get_document'){if(holdDocument)await new Promise(resolve=>releaseDocument=resolve);result={status:'success',fileName:'acc.pdf',mimeType:'application/pdf',base64:pdf('Private document fixture',2).toString('base64')};}
        else if(['save_document_review','archive_request','restore_request'].includes(data.action)){try{result=f.ctx.nextDispatch(data);}catch(error){result={status:'error',message:error.message};}if(lostReview&&data.action==='save_document_review'){lostReview=false;return route.abort();}}
        else if(data.action==='get_review_capabilities')result=oldBackend?{status:'error',message:'Aksi tidak valid.'}:{status:'success',documentReviewSupported:true,archiveSupported:true};
        else if(data.action==='get_sop')result={status:'success',document:{...doc,type:data.type}};
        else if(data.action==='logout')result={status:'success'};
        else if(await require('./next-mock.cjs')(route,data))return;
        else throw Error('Unexpected action '+data.action);
        return route.fulfill({contentType:'application/json',body:JSON.stringify(result)});
    }
    if(target.startsWith(origin))return route.continue();
    if(target.includes('chart.js'))return route.fulfill({contentType:'text/javascript',body:'window.Chart=class{static defaults={font:{}};destroy(){};constructor(){}};'});
    return route.abort();
});}
async function login(browser,role){const context=await browser.newContext({viewport:{width:1365,height:900},reducedMotion:'reduce'});await mock(context);const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());await page.goto(origin);
    if(role==='admin'){await page.click('#tab-admin');await page.fill('#input-admin-user','fixture');await page.fill('#input-admin-pass','fixture');await page.locator('#input-admin-pass').press('Enter');}
    else{await page.fill('#input-nim','A');await page.locator('#input-nim').press('Enter');}
    await page.waitForSelector('#welcome-modal',{state:'hidden'});await page.waitForFunction(()=>syncPhase==='success'&&window.IPCOSReviewTools.supported()!==null);return page;
}
(async()=>{
    const browser=await chromium.launch(),admin=await login(browser,'admin');
    await admin.evaluate(()=>openCaseDetail('fields'));await admin.click('[data-preview-index="0"]');await admin.waitForFunction(()=>document.querySelector('#case-file-preview canvas')?.dataset.rendered==='true');
    assert(await admin.locator('#case-file-preview canvas').isVisible());assert.equal(await admin.locator('#case-file-preview .pdf-accessible-text').textContent(),'Private document fixture');await admin.waitForFunction(()=>{const canvas=document.querySelector('#case-file-preview canvas');if(canvas?.dataset.rendered!=='true')return false;const pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;return pixels.some((value,i)=>i%4!==3&&value<150);});
    const bytes=await admin.evaluate(async()=>{const response=await fetch(document.querySelector('#case-file-preview .document-preview-actions a').href);return {mime:response.headers.get('content-type'),text:await response.text()};});assert.equal(bytes.mime,'application/pdf');assert(bytes.text.startsWith('%PDF-'));
    assert(await admin.locator('.document-preview-actions a').first().isVisible());pass('Admin private PDF renders with real PDF.js canvas pixels and readable text, verified bytes and an explicit fallback');
    await admin.getByRole('button',{name:'Halaman Berikutnya',exact:true}).click();await admin.waitForFunction(()=>document.querySelector('#case-file-preview canvas')?.dataset.page==='2');assert((await admin.locator('#case-file-preview .pdf-accessible-text').textContent()).includes('Page 2'));await admin.locator('.pdf-tools summary').click();await admin.getByRole('button',{name:'Perbesar PDF',exact:true}).click();await admin.waitForFunction(()=>document.querySelector('.pdf-preview-toolbar [role=status]').textContent.includes('125%'));pass('Multi-page PDF navigation and zoom render the requested page without losing controls');
    await admin.evaluate(()=>openDocPreview('https://drive.google.com/file/d/current/view'));await admin.waitForFunction(()=>document.querySelector('#case-file-preview canvas')?.dataset.rendered==='true');assert.equal(await admin.evaluate(()=>document.getElementById('modal-doc-preview').open),false);pass('Legacy admin preview routes to the authorized case API without loading Drive directly');
    await admin.selectOption('[data-review-status="0"]','revision');await admin.click('[data-save-document-review]');assert((await admin.locator('#document-review-feedback').textContent()).includes('catatan'));assert.equal(calls.filter(data=>data.action==='save_document_review').length,0);
    await admin.fill('[data-review-note="0"]','Please upload a signed form.');lostReview=true;await admin.click('[data-save-document-review]');await admin.waitForFunction(()=>!document.querySelector('[data-save-document-review]').disabled);const count=JSON.parse(f.rows[1][8]).length;await admin.click('[data-save-document-review]');await admin.waitForFunction(()=>document.getElementById('document-review-feedback').textContent.includes('tersimpan'));assert.equal(JSON.parse(f.rows[1][8]).length,count);pass('Server snapshot accepts notes on display-formatted legacy records; required reasons and lost-acknowledgement retry preserve exactly one review');
    await admin.fill('[data-review-note="0"]','Second note on the same record.');await admin.click('[data-save-document-review]');await admin.waitForFunction(()=>document.getElementById('document-review-feedback').textContent.includes('tersimpan'));assert.equal(JSON.parse(f.rows[1][8]).at(-1).reviews[0].note,'Second note on the same record.');await admin.fill('[data-review-note="0"]','Please upload a signed form.');await admin.click('[data-save-document-review]');await admin.waitForFunction(()=>document.getElementById('document-review-feedback').textContent.includes('tersimpan'));pass('The next save uses the newly confirmed server version without requiring reload');
    await admin.click('#case-detail-actions .btn-primary');await admin.click('#btn-case-submit');assert((await admin.locator('#case-action-feedback').textContent()).includes('Masih ada berkas'));assert.equal(calls.filter(data=>data.action==='update').length,0);await admin.evaluate(()=>cancelCaseAction());await admin.click('#case-detail-actions .btn-secondary');assert(await admin.locator('[name=revision-document]').first().isChecked());assert((await admin.locator('#case-revision-note').inputValue()).includes('Please upload a signed form.'));pass('A file marked for correction cannot be approved; revision selection and file-specific notes are prepared automatically');
    await admin.setViewportSize({width:390,height:844});await admin.click('[data-workspace-view="documents"]');assert(await admin.locator('#case-file-preview').isVisible());assert(!(await admin.locator('.case-action-column').isVisible()));await admin.click('[data-workspace-view="review"]');assert(await admin.locator('.case-action-column').isVisible());assert((await admin.locator('#case-revision-note').inputValue()).includes('signed'));pass('Mobile document/review switching retains unsent revision notes');
    await admin.evaluate(()=>document.getElementById('case-action-panel').dataset.dirty='false');await admin.click('.case-close');await admin.waitForSelector('#modal-case-detail',{state:'hidden'});assert.equal(await admin.evaluate(()=>caseBlobUrls.size),0);assert.equal(await admin.locator('#case-file-preview canvas').count(),0);
    const student=await login(browser,'student');await student.evaluate(()=>openCaseDetail('fields'));assert.equal(await student.locator('[data-save-document-review]').count(),0);assert((await student.locator('#document-review-tools').textContent()).includes('Please upload a signed form.'));pass('Student sees saved per-document feedback and cannot edit admin reviews');
    await admin.evaluate(()=>openCaseDetail('fields'));await admin.fill('[data-review-note="0"]','Unsaved conflict note');f.rows[1][5]='Updated by another administrator';await admin.evaluate(()=>syncDatabase());await admin.click('[data-save-document-review]');await admin.waitForFunction(()=>document.getElementById('document-review-feedback').textContent.includes('berubah'));assert.equal(await admin.locator('[data-review-note="0"]').inputValue(),'Unsaved conflict note');assert(!f.rows[1][8].includes('Unsaved conflict note'));await admin.click('[data-reload-document-review]');await admin.waitForFunction(()=>!document.getElementById('document-review-note-0').value.includes('Unsaved'));await admin.click('.case-close');await admin.waitForSelector('#modal-case-detail',{state:'hidden'});pass('Background refresh cannot change the base version of an unsaved review; conflicts retain text and explicit reload recovers');
    await student.click('.case-close');await student.waitForSelector('#modal-case-detail',{state:'hidden'});await student.evaluate(()=>switchTab(null,'pendaftaran'));await student.selectOption('#reg-jenis-utama','Outline');await student.fill('#reg-judul','International student document preview test');
    for(const id of ['file-transkrip','file-proposal'])await student.setInputFiles('#'+id,{name:id+'.pdf',mimeType:'application/pdf',buffer:pdf(id)});
    await student.click('#btn-review-registration');await student.waitForSelector('#registration-review',{state:'visible'});await student.click('[data-local-preview="file-transkrip"]');await student.waitForSelector('#local-document-preview',{state:'visible'});await student.waitForFunction(()=>document.querySelector('#local-document-preview canvas')?.dataset.rendered==='true');assert((await student.locator('#local-document-preview .pdf-accessible-text').textContent()).includes('file-transkrip'));assert.equal(calls.filter(data=>data.action==='create').length,0);await student.click('[data-close-local-preview]');await student.click('#btn-edit-registration');assert.equal(await student.evaluate(()=>document.getElementById('file-transkrip').files.length),1);pass('Student previews a selected PDF before submission, sends no upload, and retains selected files when returning to edit');
    await admin.setViewportSize({width:1365,height:900});await admin.evaluate(()=>switchTab(null,'sop-magang'));await admin.waitForSelector('[data-sop-action=edit]');await admin.click('[data-sop-action=edit]');assert((await admin.locator('#sop-translation-coverage').textContent()).includes('1/5'));await admin.click('[data-translation-target="sop-one-body"]');assert.equal(await admin.evaluate(()=>document.activeElement.id),'sop-one-bodyEn');await admin.fill('#sop-one-bodyEn','Required documents');assert((await admin.locator('#sop-translation-coverage').textContent()).includes('2/5'));await admin.click('[data-translation-target="sop-one-guide-label"]');assert.equal(await admin.evaluate(()=>document.activeElement.id),'sop-one-guide-labelEn');await admin.click('#sop-cancel');pass('English completeness counts text and link labels; missing-item links reveal and focus the correct translation input');
    await admin.evaluate(()=>switchTab(null,'admin-data'));await admin.locator('#queue-tools').evaluate(el=>el.open=true);await admin.locator('#admin-archives').evaluate(el=>el.open=true);await admin.fill('#archive-from','2026-10-01');await admin.fill('#archive-to','2026-10-31');await admin.fill('#archive-reason','Semester archive test');await admin.click('#lang-btn');await admin.selectOption('#archive-service','Proposal');assert.equal(await admin.locator('#archive-service').inputValue(),'Proposal');await admin.click('#lang-btn');assert((await admin.locator('#archive-preview-count').textContent()).startsWith('1 '));await admin.click('#archive-period-button');await admin.waitForSelector('[data-restore-request="other"]');assert.equal(f.rows[2][7],'Accepted');assert.equal(await admin.evaluate(()=>adminFilteredData.some(item=>item.id==='other')),false);
    await admin.click('[data-case-id="other"]');await admin.waitForSelector('#modal-case-detail',{state:'visible'});await admin.click('.case-close');await admin.waitForSelector('#modal-case-detail',{state:'hidden'});await admin.click('[data-restore-request="other"]');await admin.waitForFunction(()=>document.getElementById('archive-count').textContent.startsWith('0 '));assert.equal(f.rows[2][7],'Accepted');assert.equal(f.rows.length,3);pass('Period archive excludes active requests, keeps documents/history accessible, and restores without deleting rows or changing academic status');
    await admin.evaluate(()=>openCaseDetail('fields'));holdDocument=true;await admin.click('[data-preview-index="0"]');while(!releaseDocument)await new Promise(resolve=>setTimeout(resolve,10));await admin.evaluate(()=>logoutUser());releaseDocument();await admin.waitForTimeout(200);assert.equal(await admin.locator('.document-renderer').count(),0);assert.equal(await admin.evaluate(()=>caseBlobUrls.size),0);pass('Closing/logout remove local preview URLs; delayed admin file responses cannot reopen a private document');
    oldBackend=true;const legacy=await login(browser,'admin');await legacy.evaluate(()=>openCaseDetail('fields'));assert.equal(await legacy.locator('[data-save-document-review]').count(),0);await legacy.click('.case-close');await legacy.waitForSelector('#modal-case-detail',{state:'hidden'});await legacy.evaluate(()=>switchTab(null,'admin-data'));await legacy.locator('#queue-tools').evaluate(el=>el.open=true);await legacy.locator('#admin-archives').evaluate(el=>el.open=true);assert(await legacy.locator('#archive-period-button').isDisabled());assert((await legacy.locator('#archive-availability').textContent()).includes('aktivasi backend'));pass('An older backend leaves new write controls unavailable while preview and existing request actions remain usable');
    assert.deepEqual(errors,[]);fs.writeFileSync('test-results/review-tools.json',JSON.stringify({results,errors},null,2));await browser.close();
})().catch(reportFailure);
