const {chromium}=require('./browser.cjs');
const fs=require('fs'),assert=require('assert/strict');
const types=['Outline','Proposal','Pendadaran','Skripsi Jurnal','Pergantian Pembimbing'];
let services=types.map(type=>({type,enabled:true,open:'',close:'',adminDays:3,studentDays:7}));
const documents=[{label:'Transkrip',fileName:'transkrip-v1.pdf',url:'https://example.com/trans-v1.pdf',version:1},{label:'Draft Proposal',fileName:'draft-v1.pdf',url:'https://example.com/draft-v1.pdf',version:1},{label:'Transkrip',fileName:'transkrip-v2.pdf',url:'https://example.com/trans-v2.pdf',version:2}];
let records=[{id:'revision',nim:'A',nama:'Mahasiswa Uji',jenis:'Outline',status:'Revision',date:'2026-09-01T00:00:00Z',detail:'Judul Uji',link:documents.map(d=>`<a href="${d.url}">${d.label}</a>`).join('<br>'),note:JSON.stringify([{role:'mhs',time:'2026-09-01T00:00:00Z',documents:documents.slice(0,2),message:'Dikirim',status:'Pending'},{role:'mhs',time:'2026-09-04T00:00:00Z',documents:[documents[2]],message:'Perbaikan',status:'Resubmitted'},{role:'admin',time:'2026-09-05T00:00:00Z',status:'Revision',message:'Berkas yang perlu diperbaiki:\n- Transkrip\n- Draft Proposal\n\nInstruksi:\nPerbaiki keduanya.'}])},{id:'pending',nim:'B',nama:'Mahasiswa Lain',jenis:'Proposal',status:'Pending',date:'2026-09-01T00:00:00Z',detail:'Judul B',link:'',note:'[]'},{id:'new',nim:'C',nama:'Mahasiswa Baru',jenis:'Pendadaran',status:'Pending',date:new Date().toISOString(),detail:'Judul C',link:'',note:'[]'}];
let calls=[],errors=[],failSettings=false,holdReceipt=false,receiptRelease;
const checks=[];function pass(name){checks.push(name);console.log('PASS '+name)}
(async()=>{const browser=await chromium.launch({});const context=await browser.newContext({reducedMotion:"reduce",viewport:{width:1365,height:1000}});
await context.route('**/*',async route=>{const url=route.request().url();if(url.includes('script.google.com/macros/')) {const data=route.request().postDataJSON();if(await require('./next-mock.cjs')(route,data))return;calls.push(data);let result;
if(data.action==='student_login')result={status:'success',nama:'Mahasiswa Uji',token:'mhs'};
else if(data.action==='admin_login')result={status:'success',token:'admin'};
else if(data.action==='get_data')result={status:'success',registrations:structuredClone(data.token==='admin'?records:records.filter(r=>r.nim==='A')),students:[],dosens:[],contents:[],announcements:[],services,backup:data.token==='admin'?{state:'success',scheduled:true,files:3,time:new Date().toISOString(),folderId:'PRIVATE-FIXTURE'}:null};
else if(data.action==='save_services') {if(failSettings)result={status:'error',message:'Gangguan uji'};else {services=structuredClone(data.services);result={status:'success',services};}}
else if(data.action==='get_receipt') {if(holdReceipt)await new Promise(r=>receiptRelease=r);result={status:'success',fileName:'IPCOS-revision.pdf',base64:Buffer.from('%PDF-1.4\nFixture PDF\n%%EOF').toString('base64')};}
else if(data.action==='update'){const row=records.find(r=>r.id===data.id);row.status=data.status;const logs=JSON.parse(row.note);const docs=data.files.map(f=>({label:f.label,fileName:f.fileName,url:'https://example.com/'+f.fileName,version:f.label==='Transkrip'?3:2}));logs.push({role:'mhs',status:data.status,time:new Date().toISOString(),message:data.noteText,documents:docs});row.note=JSON.stringify(logs);row.link+='<br>'+docs.map(d=>`<a href="${d.url}">${d.label}</a>`).join('<br>');result={status:'success'};}
else if(data.action==='logout')result={status:'success'};else throw Error('Unexpected API '+data.action);
return route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify(result)});}
if(url.startsWith('http://127.0.0.1:8766'))return route.continue();if(url.includes('chart.js'))return route.fulfill({contentType:'text/javascript',body:'window.Chart=class {static defaults={font:{}};static getChart(){return {resize(){}}};destroy(){};constructor(){}};'});if(url.includes('example.com'))return route.fulfill({body:'Document fixture'});return route.abort();});
const admin=await context.newPage();await admin.bringToFront();admin.on('pageerror',e=>errors.push(e.message));await admin.goto('http://127.0.0.1:8766');await admin.click('#tab-admin');await admin.fill('#input-admin-user','fixture');await admin.fill('#input-admin-pass','fixture');await admin.locator('#input-admin-pass').press('Enter');await admin.waitForSelector('#welcome-modal',{state:'hidden'});await admin.waitForFunction(()=>document.querySelector('#service-settings fieldset'));
await admin.evaluate(()=>switchTab(null,'admin-data'));await admin.selectOption('#admin-status-filter','ALL');await admin.check('#admin-overdue-filter');assert.equal(await admin.locator('#table-admin-reg tr').count(),2);await admin.selectOption('#admin-type-filter','Proposal');assert.equal(await admin.locator('#table-admin-reg tr').count(),1);assert((await admin.locator('#table-admin-reg').textContent()).includes('Mahasiswa Lain'));pass('Queue filters combine service type and overdue target; new requests are excluded');
await admin.evaluate(()=>switchTab(null,'admin-master'));await admin.locator('.service-management').first().locator('summary').click();await admin.fill('#service-admin-0','12');await admin.evaluate(()=>syncDatabase());assert.equal(await admin.inputValue('#service-admin-0'),'12');failSettings=true;await admin.click('#save-service-settings');await admin.waitForFunction(()=>!document.querySelector('#save-service-settings').disabled);assert.equal(await admin.inputValue('#service-admin-0'),'12');assert(await admin.evaluate(()=>serviceSettingsEditing));failSettings=false;await admin.uncheck('#service-enabled-0');await admin.click('#save-service-settings');await admin.waitForFunction(()=>!serviceSettingsEditing);assert.equal(services[0].enabled,false);assert.equal(services[0].adminDays,12);pass('Admin edits survive refresh and save failure; valid settings persist');
await admin.locator('.service-management').nth(1).locator('summary').click();assert((await admin.locator('#backup-status').textContent()).includes('Cadangan lengkap'));assert((await admin.locator('#backup-folder').getAttribute('href')).includes('PRIVATE-FIXTURE'));await admin.bringToFront();await admin.setViewportSize({width:320,height:568});await admin.waitForFunction(()=>document.querySelector('.main-content').getBoundingClientRect().x===0 && document.querySelector('.sidebar').getBoundingClientRect().right<=0);await admin.waitForFunction(()=>!document.querySelector('.toast'));await admin.evaluate(()=>scrollTo(0,0));assert(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await admin.screenshot({path:__dirname+'/../test-results//admin-settings-mobile.png',fullPage:false});pass('Backup status and management panels fit small mobile screens');
const student=await context.newPage();await student.bringToFront();student.on('pageerror',e=>errors.push(e.message));await student.goto('http://127.0.0.1:8766');await student.fill('#input-nim','A');await student.locator('#input-nim').press('Enter');await student.waitForSelector('#welcome-modal',{state:'hidden'});await student.waitForFunction(()=>document.querySelector('#task-home [data-case-id]'));
await student.evaluate(()=>switchTab(null,'pendaftaran'));await student.selectOption('#reg-jenis-utama','Outline');assert(await student.locator('#btn-review-registration').isDisabled());await student.locator('#service-availability [data-case-id]').click();await student.waitForSelector('#modal-case-detail',{state:'visible'});assert.equal(await student.locator('#case-detail-content h4').first().textContent(),'Versi terbaru');assert.equal(await student.locator('#case-detail-content .document-version').count(),3);const files=student.locator('#case-detail-content .case-content-block').last();assert((await files.textContent()).includes('Versi 2'));assert.equal(await files.locator('details .document-version').count(),1);await files.locator('button[data-preview-index="2"]').click();assert.equal(await student.locator('#case-file-preview iframe').getAttribute('src'),'https://example.com/trans-v2.pdf');pass('Duplicate redirects to existing case, latest versions are prominent and prior files remain accessible');
const download=student.waitForEvent('download');await student.locator('#case-detail-content [data-receipt-id]').click();const receipt=await download;assert.equal(receipt.suggestedFilename(),'IPCOS-revision.pdf');const pdf=fs.readFileSync(await receipt.path());assert.equal(pdf.subarray(0,5).toString(),'%PDF-');pass('Student can re-download PDF proof from an existing case');
await student.locator('#modal-case-detail button').filter({hasText:'Upload Perbaikan'}).click();await student.locator('[name="correction-complete"]').nth(0).check();await student.locator('[name="correction-complete"]').nth(1).check();await student.setInputFiles('#case-reply-files',[{name:'trans-v3.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 trans\n%%EOF')},{name:'draft-v2.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 draft\n%%EOF')}]);await student.fill('#case-reply-note','Keduanya diperbaiki');await student.selectOption('#revision-label-0','Transkrip');await student.selectOption('#revision-label-1','Transkrip');await student.click('#btn-case-submit');assert.equal(calls.filter(c=>c.action==='update').length,0);await student.selectOption('#revision-label-1','Draft Proposal');await student.click('#btn-case-submit');await student.waitForFunction(()=>document.querySelector('#case-detail-content')?.textContent.includes('Versi 3'));assert.equal(calls.filter(c=>c.action==='update').length,1);assert.deepEqual(calls.find(c=>c.action==='update').files.map(f=>f.label),['Transkrip','Draft Proposal']);pass('Closed service still permits revisions; distinct labels map two uploads to the correct document versions');
await student.bringToFront();await student.setViewportSize({width:390,height:844});await student.waitForFunction(()=>document.querySelector('.main-content').getBoundingClientRect().x===0 && document.querySelector('.sidebar').getBoundingClientRect().right<=0);await student.waitForFunction(()=>!document.querySelector('.toast'));assert(await student.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await student.screenshot({path:__dirname+'/../test-results//student-versions-mobile.png',fullPage:false});assert(await student.locator('#modal-case-detail .case-detail-card').evaluate(e=>e.scrollWidth<=e.clientWidth));
let downloads=0;student.on('download',()=>downloads++);holdReceipt=true;await student.locator('#case-detail-content [data-receipt-id]').click();while(!receiptRelease)await new Promise(r=>setTimeout(r,10));student.on('dialog',d=>d.accept());await student.evaluate(()=>logoutUser());await student.waitForSelector('#welcome-modal',{state:'visible'});receiptRelease();await student.waitForTimeout(300);assert.equal(downloads,0);assert.equal(await student.locator('#backup-folder').getAttribute('href'),null);assert.equal(await student.locator('#service-settings').textContent(),'');assert.equal(await student.evaluate(()=>sessionStorage.getItem('ipcos_registrations')),null);pass('Late PDF response cannot download after logout; settings and private backup links are cleared');
assert.deepEqual(errors,[]);pass('No JavaScript runtime errors in new workflow features');fs.writeFileSync(__dirname+'/../test-results//services-results.json',JSON.stringify({checks,errors},null,2));await browser.close();})().catch(require('./browser.cjs').reportFailure);
