const {chromium}=require('./browser.cjs');
const assert=require('assert/strict');
(async()=>{
const browser=await chromium.launch({});
const context=await browser.newContext({reducedMotion:"reduce",viewport:{width:1365,height:900}});
let failRead=false,failUpdate=false,holdCreate=false,createRelease,errors=[],calls=[];
let records=Array.from({length:25},(_,i)=>({id:'q'+i,nim:'B',nama:'Mahasiswa Uji '+i,jenis:'Proposal',status:'Pending',date:'2026-10-05T01:00:00Z',detail:'Contoh Uji',link:'',note:'[]'}));
await context.route('**/*',async route=>{
 const url=route.request().url(); if(url.includes('script.google.com/macros/')) {
 const data=route.request().postDataJSON();if(await require('./next-mock.cjs')(route,data))return;calls.push(data); let result;
 if(data.action==='admin_login') result={status:'success',token:'admin'};
 else if(data.action==='student_login') result={status:'success',token:'student-A',nama:'Mahasiswa Uji'};
 else if(data.action==='get_data')result=failRead?{status:'error',message:'Gangguan uji'}:{status:'success',registrations:data.token==='admin'?records:records.filter(r=>r.nim==='A'),students:[],dosens:[],contents:[],announcements:[]};
 else if(data.action==='update')result=failUpdate?{status:'error',message:'Gangguan uji'}:{status:'success'};
 else if(data.action==='create'){if(holdCreate)await new Promise(r=>createRelease=r);result={status:'success',id:'created',date:new Date().toISOString()};}
 else if(data.action==='logout')result={status:'success'};
 else throw Error('Unexpected mutation '+data.action);
 return route.fulfill({contentType:'application/json',body:JSON.stringify(result)});
 }
 if(url.startsWith('http://127.0.0.1:8766'))return route.continue();return route.abort();
});
const admin=await context.newPage();await admin.bringToFront();admin.on('pageerror',e=>errors.push(e.message));let permit=false;admin.on('dialog',d=>permit?d.accept():d.dismiss());
await admin.goto('http://127.0.0.1:8766');await admin.click('#tab-admin');await admin.fill('#input-admin-user','fixture');await admin.fill('#input-admin-pass','fixture');await admin.locator('#input-admin-pass').press('Enter');await admin.waitForSelector('#welcome-modal',{state:'hidden'});await admin.waitForFunction(()=>syncPhase==='success');assert((await admin.locator('#sync-status').textContent()).includes('Terakhir diperbarui'));
failRead=true;await admin.evaluate(()=>syncDatabase());assert((await admin.locator('#sync-status').textContent()).includes('gagal'));assert.equal(await admin.locator('#table-admin-reg tr').count(),10);failRead=false;await admin.evaluate(()=>syncDatabase());console.log('PASS Sync success/failure is visible and failed refresh retains queue');
await admin.evaluate(()=>switchTab(null,'admin-data'));await admin.selectOption('#admin-status-filter','ALL');await admin.evaluate(()=>document.getElementById('queue-advanced').open=true);await admin.selectOption('#admin-type-filter','Proposal');await admin.click('#admin-btn-next');assert((await admin.locator('#admin-page-info').textContent()).includes('2 / 3'));await admin.bringToFront();await admin.reload();await admin.bringToFront();await admin.waitForSelector('#welcome-modal',{state:'hidden'});await admin.waitForFunction(()=>syncPhase==='success');assert.equal(await admin.inputValue('#admin-status-filter'),'ALL');assert.equal(await admin.inputValue('#admin-type-filter'),'Proposal');assert.equal(await admin.evaluate(()=>currentAdminPage),2);await admin.evaluate(()=>openCaseDetail('q1'));await admin.click('.case-close');assert.equal(await admin.evaluate(()=>currentAdminPage),2);console.log('PASS Admin filters, sorting and page survive reload and closing case');
await admin.evaluate(()=>openCaseDetail('q1'));await admin.locator('#case-detail-actions button').filter({hasText:'Minta Revisi'}).click();await admin.fill('#case-revision-note','Catatan khusus.');await admin.selectOption('#revision-template','certified');assert((await admin.inputValue('#case-revision-note')).startsWith('Catatan khusus.'));assert((await admin.inputValue('#case-revision-note')).includes('disahkan'));assert.equal(await admin.locator('[name="revision-document"]:checked').count(),0);await admin.locator('[name="revision-document"]').first().check();await admin.click('.case-close');assert(await admin.locator('#modal-case-detail').isVisible());assert((await admin.inputValue('#case-revision-note')).includes('Catatan khusus.'));await admin.screenshot({path:__dirname+'/../test-results//revision-templates.png',fullPage:false});failUpdate=true;await admin.click('#btn-case-submit');await admin.waitForFunction(()=>document.querySelector('#case-action-feedback-steps')?.dataset.stage==='uncertain');assert((await admin.inputValue('#case-revision-note')).includes('Catatan khusus.'));assert(!await admin.locator('#btn-case-submit').isDisabled());failUpdate=false;permit=true;await admin.click('.case-close');console.log('PASS Editable template appends notes; cancel-close and failed send preserve input');
const before=calls.filter(c=>c.action==='get_data').length;
await admin.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await admin.evaluate(()=>syncTimer),null);await admin.evaluate(()=>silentSyncDatabase());assert.equal(calls.filter(c=>c.action==='get_data').length,before);
await admin.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await admin.waitForFunction(()=>syncPhase==='success');assert.equal(calls.filter(c=>c.action==='get_data').length,before+1);assert.notEqual(await admin.evaluate(()=>syncTimer),null);console.log('PASS Hidden tab stops timer/read; visible tab refreshes once and resumes scheduling');
await admin.evaluate(()=>window.dispatchEvent(new Event('offline')));assert((await admin.locator('#sync-status').textContent()).includes('Offline'));await admin.evaluate(()=>window.dispatchEvent(new Event('online')));await admin.waitForFunction(()=>syncPhase==='success');console.log('PASS Offline and reconnect states match the actual sync lifecycle');
await admin.evaluate(()=>logoutUser());await admin.waitForSelector('#welcome-modal',{state:'visible'});assert.equal(await admin.evaluate(()=>sessionStorage.getItem('ipcos_queue_view')),null);assert.equal(await admin.inputValue('#admin-type-filter'),'');assert.equal(await admin.evaluate(()=>lastSyncTime),'');assert(await admin.locator('#sync-status').isHidden());console.log('PASS Logout clears queue preferences, time and private state');
const student=await context.newPage();await student.bringToFront();student.on('pageerror',e=>errors.push(e.message));let leave=false;student.on('dialog',d=>leave?d.accept():d.dismiss());await student.goto('http://127.0.0.1:8766');await student.fill('#input-nim','A');await student.locator('#input-nim').press('Enter');await student.waitForSelector('#welcome-modal',{state:'hidden'});await student.evaluate(()=>switchTab(null,'pendaftaran'));await student.selectOption('#reg-jenis-utama','Proposal');await student.fill('#reg-judul','Judul uji');await student.locator('#file-acc-sempro').setInputFiles({name:'acc.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 test\n%%EOF')});await student.evaluate(()=>switchTab(null,'dashboard'));assert(await student.locator('#pendaftaran').isVisible());assert.equal(await student.inputValue('#reg-judul'),'Judul uji');assert.equal(await student.evaluate(()=>window.dispatchEvent(new Event('beforeunload',{cancelable:true}))),false);console.log('PASS Unsent registration guards navigation and unload; cancelling retains file/text');
holdCreate=true;await student.click('#btn-review-registration');await student.click('#btn-submit-registration');await student.waitForFunction(()=>document.querySelector('#form-submit-status-steps')?.dataset.stage==='sending');assert(await student.locator('#btn-submit-registration').isDisabled());while(!createRelease)await new Promise(r=>setTimeout(r,10));createRelease();await student.waitForFunction(()=>document.querySelector('#form-submit-status-steps')?.dataset.stage==='confirmed');assert.equal(await student.evaluate(()=>registrationDirty),false);assert.equal(await student.evaluate(()=>window.dispatchEvent(new Event('beforeunload',{cancelable:true}))),true);console.log('PASS Upload is pending until server confirms; success clears leave warnings');
await admin.screenshot({path:__dirname+'/../test-results//workflow-admin.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS No new JavaScript errors for both roles');await browser.close();
})().catch(require('./browser.cjs').reportFailure);
